# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/amsozzer/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/amsozzer/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amsozzer/cpp/CMakeFiles /Users/amsozzer/cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amsozzer/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PlusWeb

# Build rule for target.
PlusWeb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PlusWeb
.PHONY : PlusWeb

# fast build rule for target.
PlusWeb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/build
.PHONY : PlusWeb/fast

src/HttpRequest.o: src/HttpRequest.cpp.o
.PHONY : src/HttpRequest.o

# target to build an object file
src/HttpRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpRequest.cpp.o
.PHONY : src/HttpRequest.cpp.o

src/HttpRequest.i: src/HttpRequest.cpp.i
.PHONY : src/HttpRequest.i

# target to preprocess a source file
src/HttpRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpRequest.cpp.i
.PHONY : src/HttpRequest.cpp.i

src/HttpRequest.s: src/HttpRequest.cpp.s
.PHONY : src/HttpRequest.s

# target to generate assembly for a file
src/HttpRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpRequest.cpp.s
.PHONY : src/HttpRequest.cpp.s

src/HttpResponse.o: src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.o

# target to build an object file
src/HttpResponse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.cpp.o

src/HttpResponse.i: src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.i

# target to preprocess a source file
src/HttpResponse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.cpp.i

src/HttpResponse.s: src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.s

# target to generate assembly for a file
src/HttpResponse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.cpp.s

src/HttpServer.o: src/HttpServer.cpp.o
.PHONY : src/HttpServer.o

# target to build an object file
src/HttpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpServer.cpp.o
.PHONY : src/HttpServer.cpp.o

src/HttpServer.i: src/HttpServer.cpp.i
.PHONY : src/HttpServer.i

# target to preprocess a source file
src/HttpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpServer.cpp.i
.PHONY : src/HttpServer.cpp.i

src/HttpServer.s: src/HttpServer.cpp.s
.PHONY : src/HttpServer.s

# target to generate assembly for a file
src/HttpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/HttpServer.cpp.s
.PHONY : src/HttpServer.cpp.s

src/RouteRegistry.o: src/RouteRegistry.cpp.o
.PHONY : src/RouteRegistry.o

# target to build an object file
src/RouteRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/RouteRegistry.cpp.o
.PHONY : src/RouteRegistry.cpp.o

src/RouteRegistry.i: src/RouteRegistry.cpp.i
.PHONY : src/RouteRegistry.i

# target to preprocess a source file
src/RouteRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/RouteRegistry.cpp.i
.PHONY : src/RouteRegistry.cpp.i

src/RouteRegistry.s: src/RouteRegistry.cpp.s
.PHONY : src/RouteRegistry.s

# target to generate assembly for a file
src/RouteRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/RouteRegistry.cpp.s
.PHONY : src/RouteRegistry.cpp.s

src/trie.o: src/trie.cpp.o
.PHONY : src/trie.o

# target to build an object file
src/trie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/trie.cpp.o
.PHONY : src/trie.cpp.o

src/trie.i: src/trie.cpp.i
.PHONY : src/trie.i

# target to preprocess a source file
src/trie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/trie.cpp.i
.PHONY : src/trie.cpp.i

src/trie.s: src/trie.cpp.s
.PHONY : src/trie.s

# target to generate assembly for a file
src/trie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/trie.cpp.s
.PHONY : src/trie.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlusWeb.dir/build.make CMakeFiles/PlusWeb.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... PlusWeb"
	@echo "... src/HttpRequest.o"
	@echo "... src/HttpRequest.i"
	@echo "... src/HttpRequest.s"
	@echo "... src/HttpResponse.o"
	@echo "... src/HttpResponse.i"
	@echo "... src/HttpResponse.s"
	@echo "... src/HttpServer.o"
	@echo "... src/HttpServer.i"
	@echo "... src/HttpServer.s"
	@echo "... src/RouteRegistry.o"
	@echo "... src/RouteRegistry.i"
	@echo "... src/RouteRegistry.s"
	@echo "... src/trie.o"
	@echo "... src/trie.i"
	@echo "... src/trie.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

